name: env_fl
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip=22.2.2
  - pytorch-cuda=11.7
  - pytorch=1.13.0
  - torchvision=0.14.0
  - torchaudio=0.13.0
  - pip:
    - tqdm==4.66.1
    - scikit-learn==1.3.1
    - flwr==1.6
    - albumentations==1.3.1
    - omegaconf==2.3
    - hydra-core==1.3.2
    - wandb==0.13.9